pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }
    plugins {
        id 'com.android.application' version '8.7.3'
        id 'com.chaquo.python' version '25.3.1'
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "ShimaTube"
include ':app'
