plugins {
    id 'com.android.application'
}

android {
    namespace 'org.shimatube.app'
    compileSdk 34

    defaultConfig {
        applicationId "org.shimatube.app"
        minSdk 26
        targetSdk 34
        versionCode 23
        versionName "19.4"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    buildFeatures {
        buildConfig true
    }

    aaptOptions {
        noCompress "tar.gz"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // Termux環境ではNDKのllvm-stripがx86_64で実行不可のためスキップ
    packagingOptions {
        doNotStrip '**/*.so'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.8.0'
}
